import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/home.css"
import "./styles/nav.css"
import "./styles/signup.css"
import "./styles/login.css"
import "./styles/verification.css"
import "./styles/forgetpassword.css"
// import "./styles/reset.css"
import Navbar from "./nav/page";
import { AuthProvider } from "./usecontext/AuthContext.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Authentication app",
  description: "Generated by create Mrdev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
           <Navbar />
          {children}</AuthProvider>
      </body>
    </html>
  );
}
